version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./besu
      dockerfile: ${BESU_DOCKERFILE}
      args:
        - BUILD_TARGET=${BESU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${BESU_DOCKER_TAG}
    image: besu:local-merge
    user: besu
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - besuexecution-data:/var/lib/besu
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    expose:
      - ${EL_RPC_PORT}/tcp
      - ${EL_WS_PORT}/tcp
      - 9545/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - /opt/besu/bin/besu
      - --data-path
      - /var/lib/besu
      - --p2p-port
      - ${EL_P2P_PORT}
      - --rpc-http-enabled
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${EL_WS_PORT}
      - --host-allowlist=*
      - --logging
      - ${LOG_LEVEL}
      - --metrics-enabled
      - --metrics-host
      - 0.0.0.0
        #      - --Xdata-storage-format=BONSAI
      - --genesis-file
      - "/configs/besu_genesis.json"
      - --network-id
      - ${NETWORK_ID}
      - --bootnodes
      - ${ENODE}
      - --Xmerge-support
      - "true"
      - --miner-coinbase
      - ${REWARDS_TO}
  eth:
    depends_on:
      - execution
volumes:
  besuexecution-data:
