version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./teku
      args:
        - BUILD_TARGET=${TEKU_SRC_BUILD_TARGET}
        - DOCKER_TAG=${TEKU_DOCKER_TAG}
      dockerfile: ${TEKU_DOCKERFILE}
    image: teku:local-merge
    user: teku
    stop_grace_period: 1m
    volumes:
      - teku-data:/var/lib/teku
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
    expose:
      - 8008/tcp
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - /opt/teku/bin/teku
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --eth1-endpoints=${EL_NODE}
      - --p2p-port=${CL_P2P_PORT}
      - --p2p-peer-upper-bound=${TEKU_PEER_COUNT}
      - --logging=${LOG_LEVEL}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=5052
      - --metrics-enabled=true
      - --metrics-port=8008
      - --metrics-interface=0.0.0.0
      - --metrics-host-allowlist=*
        #      - --network=/configs/config.yaml
        #- --initial-state=/configs/genesis.ssz
      - --network=${NETWORK}
        #- --initial-state=/configs/genesis.ssz
      - --Xee-endpoint=${EL_NODE}
      - --data-storage-non-canonical-blocks-enabled=true
        #      - --Xnetwork-merge-total-terminal-difficulty-override=${TOTAL_TERMINAL_DIFFICULTY}
      - --Xvalidators-proposer-default-fee-recipient=${REWARDS_TO}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cl.service=cl
      - traefik.http.routers.cl.entrypoints=websecure
      - traefik.http.routers.cl.rule=Host(`${CL_HOST}.${DOMAIN}`)
      - traefik.http.routers.cl.tls.certresolver=letsencrypt
      - traefik.http.services.cl.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  teku-data:
